---
title: "Informe PRYE"
author: "Fredy David Arias, Brayan Rojas, Jose Luis Gomez"
date: "5/11/2019"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# INFORME PARA LA DIFERENCIA DE MEDIAS
La distribucion muestral de la *diferencia de dos medias* es el problema estadistico que se va a tratar en este informe. Como se puede deducir, el problema consiste en el planteamiento de una distribucion normal para dos poblaciones muestrales con diferencias en las medias muestrales; se vera atraves de diferentes ejemplos como esta aplicacion puede ir variando he incluso se puede desarrollar diferentes ejemplos con una sola media poblacional, como se vera mas adelante. En la mayoria de los casos se puede realizar una aproximacion con el teorema del limete central, amplificando dicho teorema, y suponiendo que las medias de las dos muestras son iguales la ecuacion resultante termina siendo:

$$
\ Z = \frac{(\bar{X_1}-\bar{X_2})-(μ_1 - μ_2)}{\sqrt{\frac{(σ^2_1)}{n_1}}}
$$
A mediada que se va avanzando en los ejercicios y en las unidades de nuestro texto guia *probabilidad y estadística para ingeniería y ciencia* podemos ver como el contexto de los ejercicios va cambiando y nos va llevando a analizar diferentes ideas de realizacion de problemas. Pasando por intervalos de confianza y simulaciones que llevan a analizar el comportamiento de dos tomas muestrales. 
Podemos decir que el conocimiento del intervalo en el que se encuentra una diferencia de dos medias poblacionales nos sirve principalmente para poder comprender que tan similares o que tan variantes son estas dos muestras; dependiendo del contexto brindado por el ejercicio se puede decir que se acepta o se rechaza el experimiento. Uno de los criterios mas importantes y que resaltamos en cada una de nuestras simulaciones, es cuando *el cero se encuentra contenido en el intervalo*, esto nos da a entender en como estas dos muestras se encuentran claramente relacionadas y con cada experimento aleatorio se genera una pequeña brecha entre las dos medias, esto quiere decir que los tamaños de muestra escogidos y las varianzas generadas aleatoriamente guardan una relación, por esto nos sirve conocer la diferencia de dos medias poblacionales y en este caso el intervalo en el que se encuentra. 
Para esto se usó la siguiente ecuacion:

$$
(\bar{X_1}-\bar{X_2})-t_{α/2}*\sqrt{\frac{S_1^2}{n_1}+ \frac{S_2^2}{n_2}} < μ_1-μ_2 < (\bar{X_1}-\bar{X_2})+t_{α/2}*\sqrt{\frac{S_1^2}{n_1}+ \frac{S_2^2}{n_2}}
$$
Donde el \bar{X} representa las medias de las muestras aleatorias extraidas, de igual manera \S_1 representa la desviacion estandar al cuadrado de la poblacion experimental y n representa el numero de la poblacion. El \t_{α/2} representa la distribucion muestral que usaremos que en este caso es la t con (1-α)*100% rango de confiabilidad. Estos datos salen de una tabla. 


*Para los siguientes ejercicios se hará las respectivas simulaciones_*

## Ejercicio 8.33
_El benceno es una sustancia química altamente tóxica para los seres humanos. Sin embargo, se utiliza en la fabricación de medicamentos, de tintes y de recubrimientos, así como en la peletería. Las regulaciones del gobierno establecen que el contenido de benceno en el agua que resulte de cualquier proceso de producción en el que participe esta sustancia no debe exceder 7950 partes por millón (ppm). Para un proceso particular de interés, un fabricante recolectó una muestra de agua 25 veces de manera aleatoria y el promedio muestral ¯ x fue de 7960 ppm. A partir de los datos históricos, se sabe que la desviación estándar σ es 100 ppm. a) ¿Cuál es la probabilidad de que el promedio muestral en este experimento exceda el límite establecido por el gobierno, si la media de la población es igual al límite? Utilice el teorema del límite central. b) ¿La ¯ x = 7960 observada en este experimento es fi rme evidencia de que la media de la población en este proceso excede el límite impuesto por el gobierno? Responda calculando P( ¯ X ≥ 7960 | μ =7950).  Suponga que la distribución de la concentración de benceno es normal._ 

~~~
mu<- 7950
valor<-1000
sigma <-100
n <-25
xbarra1 <- 20.5
xbarra2 <- 24.5
vector <-1:valor
vector2 <- 1:valor

for(i in vector){
  vector[i]<- mean(rnorm(n,mu,sigma))
}
for(y in vector2){
  vector2[y]<- mean(rnorm(n,mu,sigma))
}
vectorfin<- 1:valor
contadorA<-0
vectorfin<-vector-vector2
for(c in 1:valor){
  if(vectorfin[c]>=0){
    contadorA=contadorA+1
  }
}
contadorA
~~~


## Ejercicio 8.69
_Se consideran dos propulsores de combustible sólido distintos, el tipo A y el tipo B, para una actividad del programa espacial. Las velocidades de combustión en el propulsor son fundamentales. Se toman muestras aleatorias de 20 especímenes de los dos propulsores con medias muestrales de 20.5 cm/s para el propulsor A y de 24.50 cm/s para el propulsor B. Por lo general se supone que la variabilidad en la velocidad de combustión es casi igual para los dos propulsores y que es determinada por una desviación estándar de población de 5 cm/s. Suponga que la velocidad de combustión para cada propulsor es aproximadamente normal, por lo cual se debería utilizar el teorema del límite central. Nada se sabe acerca de las medias poblacionales de las dos velocidades de combustión y se espera que este experimento revele algo sobre ellas_

~~~
mu<- 0
valor<-1000
sigma <-5
n <-20
xbarra1 <- 20.5
xbarra2 <- 24.5
vector <-1:valor
vector2 <- 1:valor

for(i in vector){
  vector[i]<- mean(rnorm(n,mu,sigma))
}
for(y in vector2){
  vector2[y]<- mean(rnorm(n,mu,sigma))
}
vectorfin<- 1:valor
contador<-0
vectorfin<-vector-vector2
for(c in 1:valor){
  if(vectorfin[c]>=4){
    contador=contador+1
  }
}
contador
~~~

## Ejercicio 9.35
_Una muestra aleatoria de tamaño n1 = 25, tomada de una población normal con una desviación estándar σ1 = 5, tiene una media x1 = 80. Una segunda muestra aleatoria de tamaño n2 = 36, que se toma de una población normal diferente con una desviación estándar σ2 = 3, tiene una media x2 = 75. Calcule un intervalo de confi anza del 94% para μ1 – μ2_

~~~
z<-1.18
valor<-1000
xbarra1<-1:valor
xbarra2<-1:valor
sigma1<- 1:valor
sigma2<- 1:valor
n1<- 1:valor
n2<- 1:valor
resultadoInferior<- 1:valor
resultadoSuperior<- 1:valor
contador<-0
for(x in 1:valor){
  xbarra1[x]<- runif(1, min=70, max=90)
  xbarra2[x]<- runif(1, min=65, max=85)
  sigma1[x]<- runif(1, min=4, max=6)
  sigma2[x]<- runif(1, min=2, max=4)
  n1[x]<- runif(1, min=15, max=35)
  n2[x]<- runif(1, min=26, max=46)
  xbarra<- xbarra1[x]-xbarra2[x]
  divicion1<- (sigma1[x]^2)/n1[x]
  divicion2<- (sigma2[x]^2)/n2[x]
  suma<-divicion1+divicion2
  raiz<- sqrt(suma)
  resultadoInferior[x]<- xbarra-(z*raiz)
  resultadoSuperior[x]<- xbarra+(z*raiz)
  if (resultadoInferior[x]<0){
    if (resultadoSuperior[x]>0){
      contador<- contador+1
    }
  }
}
tabla <- data.frame(cbind(resultadoInferior, resultadoSuperior))
contador
~~~

## Ejercicio 9.39
_Los estudiantes pueden elegir entre un curso de física de tres semestres-hora sin laboratorio y un curso de cuatro semestres-hora con laboratorio. El examen 
fi nal escrito es el mismo para ambos cursos. Si 12 estudiantes del curso con laboratorio obtienen una calificación promedio de 84, con una desviación estándar de 4, y 18 estudiantes del grupo sin laboratorio obtienen una calificación promedio de 77, con una desviación estándar de 6, calcule un intervalo de confi anza del 99% para la diferencia entre las calificaciones promedio para ambos cursos. Suponga que las poblaciones se distribuyen de forma aproximadamente normal y que tienen varianzas iguales_

~~~
z<- 2.763*5.305
valor<-1000
xbarra1<-1:valor
xbarra2<-1:valor
sigma1<- 1:valor
sigma2<- 1:valor
n1<- 1:valor
n2<- 1:valor
resultadoInferior<- 1:valor
resultadoSuperior<- 1:valor
contador<-0
for(x in 1:valor){
  xbarra1[x]<- runif(1, min=6, max=8)
  xbarra2[x]<- runif(1, min=6, max=8)
  sigma1[x]<- runif(1, min=1, max=2)
  sigma2[x]<- runif(1, min=1, max=2)
  n1[x]<- runif(1, min=2, max=22)
  n2[x]<- runif(1, min=8, max=28)
  xbarra<- xbarra1[x]-xbarra2[x]
  divicion1<- (sigma1[x]^2)/n1[x]
  divicion2<- (sigma2[x]^2)/n2[x]
  suma<-divicion1+divicion2
  raiz<- sqrt(suma)
  resultadoInferior[x]<- xbarra-(z*raiz)
  resultadoSuperior[x]<- xbarra+(z*raiz)
  if (resultadoInferior[x]<0){
    if (resultadoSuperior[x]>0){
      contador<- contador+1
    }
  }
}
tabla <- data.frame(cbind(resultadoInferior, resultadoSuperior))
contador 
~~~

## Ejercicio 9.45
_El gobierno otorgó fondos para los departamentos de agricultura de 9 universidades para probar las capacidades de cosecha de dos nuevas varied ades de trigo.Calcule un intervalo de confi anza del 95% para la diferencia media entre las cosechas de las dos variedades, suponiendo que las diferencias entre las cosechas se distribuyen de forma aproximadamente normal. Explique por qué es necesario el pareado en este problema_

~~~
z=2.306
n<-9
valor<-1000
resultadoInferior<- 1:valor
resultadoSuperior<- 1:valor
contador<-0
for( i in 1:valor){
  valores<- 1:n
  valores1<- 1:n
  for(x in 1:n){
    valores1[x]<- runif(1, min=0, max=100)
    valores[x]<- runif(1, min=0, max=100)
  }
  finValor <- valores- valores1
  s<- sd(finValor)
  mu<- mean(finValor)
  resultadoInferior[i]= mu-(z*(s/sqrt(n)))
  resultadoSuperior[i]= mu+(z*(s/sqrt(n)))
  if (resultadoInferior[x]<0){
    if (resultadoSuperior[x]>0){
      contador<- contador+1
    }
  }
}
contador
valores
~~~

#Ejercicio 9.46 

_Calcule un intervalo de confi anza del 90% para la diferencia entre la duración promedio de las películas que producen las dos empresas. Suponga que las diferencias en la duración se distribuyen de forma aproximadamente normal y que tienen varianzas distintas_

~~~
z=1.894
n<-9
valor<-1000
resultadoInferior<- 1:valor
resultadoSuperior<- 1:valor
contador<-0
for( i in 1:7){
  valores<- 1:5
  valores1<- 1:7
  for(x in 1:7){
    valores1[x]<- runif(1, min=0, max=100)
  }
  for(x in 1:5){
    valores[x]<- runif(1, min=0, max=100)
  }
  finValor <- valores- valores1
  s<- sd(finValor)
  mu<- mean(finValor)
  resultadoInferior[i]= mu-(z*(s/sqrt(n)))
  resultadoSuperior[i]= mu+(z*(s/sqrt(n)))
  if (resultadoInferior[x]<0){
    if (resultadoSuperior[x]>0){
      contador<- contador+1
    }
  }
}
contador
valores
~~~

## Ejercicio 10.30
_Una muestra aleatoria de tamaño n1 = 25, tomada de una población normal con una desviación estándar σ1 = 5.2, tiene una media ¯ x1 = 81. Una segunda muestra aleatoria de tamaño n2 = 36, que se toma de una población normal diferente con una desviación estándar σ2 = 3.4, tiene una media ¯ x2 = 76. Pruebe la hipótesis de que μ1 = μ2 contra la alternativa μ1 ≠ μ2. Cite un valor P en su conclusión. _

~~~
mu<- 0
valor<-1000
sigma <- 5.2
sigma2<- 3.4
n <- 25
n2<- 36
xbarra1 <- 81
xbarra2 <- 76
vector <-1:valor
vector2 <- 1:valor

for(i in vector){
  vector[i]<- mean(rnorm(n,mu,sigma))
}
for(y in vector2){
  vector2[y]<- mean(rnorm(n2,mu,sigma2))
}
vectorfin<- 1:valor
contador<-0
vectorfin<-vector-vector2
for(c in 1:valor){
  if(vectorfin[c]>=4.22){
    contador=contador+1
  }
}
contador
~~~

#Ejercicio 10.28 
_De acuerdo con Chemical Engineering, una propiedad importante de la fibra es su absorbencia de agua. Se encontró que el porcentaje promedio de absorción de 25 pedazos de fibra de algodón seleccionados al azar es 20, con una desviación estándar de 1.5. Una muestra aleatoria de 25 pedazos de acetato reveló un porcentaje promedio de 12 con una desviación estándar de 1.25. ¿Existe evidencia sólida de que el porcentaje promedio de absorción de la población es significativamente mayor para la fibra de algodón que para el acetato? Suponga que el porcentaje de absorbencia se distribuye de forma casi normal y que las varianzas de la población en el porcentaje de absorbencia para las dos fibras son iguales. Utilice un nivel de significancia de 0.05_

~~~
 n-25
  df<-48
  ncp<-0
  contador<-0
  for (v in 1:1000){
    
  vector<- rt(n,df,ncp)
  for (x in 1:n){
    resultado<-8/(vector[x]*sqrt(1/25))
    if(resultado>0){
      contador<- contador+1
    }
  }
  }
  contador
~~~

## Ejercicio 10.42
_Cinco muestras de una sustancia ferrosa se usaron para determinar si existe una diferencia entre un análisis químico de laboratorio y un análisis de fluorescencia de rayos X del contenido de hierro. Cada muestra se dividió en dos submuestras y se aplicaron los dos tipos de análisis. Suponga que las poblaciones son normales y pruebe, al nivel de significancia de 0.05, si los dos métodos de análisis dan, en promedio, el mismo resultado_

~~~
Problema sin simulación.
~~~


